title: Néstor Gómez | Desarrollador de Software
email: ing.nestorgt@gmail.com
year: 2026

# Configuración básica de Jekyll
markdown: kramdown
theme: null

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 15
  permalink: '/pages/blog/pagina/:num/'
  title: ':title - Página :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
